[view_settings]
show_cursor = true
show_cursor_during_playback = false
highlight_viewed_note = true
select_last_inserted_note = true
show_gimmicks = true
show_gimmicks_during_playback = true
hispeed_setting = 1.5
volume = 100
dark_mode = false
show_measure_buttons = false
slider_scroll_factor = 1
use_space_to_play_sink = false
render_safely_but_slowly = true
handle_overflow_position_numeric_scroll = false
handle_overflow_size_numeric_scroll = false
place_note_on_drag = true
show_notes_on_beat = false
language = "en-US"
show_beat_visual_settings = true
show_slide_snap_arrows = true
guide_line_selection = 1
beat_division = 1.0
note_scale_multiplier = 1.0
slide_note_rotation_speed = 1.0
editor_refresh_rate = 60
show_note_links = true
show_mask_notes = true
[save_settings]
auto_save_interval = 1
[hotkey_settings]
touch_hotkey = 35
slide_left_hotkey = 36
slide_right_hotkey = 37
snap_up_hotkey = 38
snap_down_hotkey = 39
chain_hotkey = 40
hold_hotkey = 41
play_hotkey = 59
[sound_settings]
hitsound_enabled = false
hitsound_path = ""
hitsound_volume = 50
hitsound_additional_offset_ms = 0
[cursor_settings]
is_active_cursor_tracking_enabled = false
[color_settings]
color_note_tap = "#FFFF00FF"
color_note_chain = "#FFCCBE2D"
color_note_slide_cw = "#FFFF8000"
color_note_slide_ccw = "#FF32CD32"
color_note_snap_fw = "#FFFF0000"
color_note_snap_bw = "#FF00FFFF"
color_note_hold_start = "#FF8C6400"
color_note_hold_segment = "#FFDCB932"
color_note_hold_gradient0 = "#BEDCA000"
color_note_hold_gradient1 = "#BEDCB932"
