//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BAKKA_Editor.Assets {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BAKKA_Editor.Assets.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Mask.
        /// </summary>
        public static string AddMask {
            get {
                return ResourceManager.GetString("AddMask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beat:.
        /// </summary>
        public static string Beat {
            get {
                return ResourceManager.GetString("Beat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bonus Get.
        /// </summary>
        public static string BonusGet {
            get {
                return ResourceManager.GetString("BonusGet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BPM Change.
        /// </summary>
        public static string BpmChange {
            get {
                return ResourceManager.GetString("BpmChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C-Clockwise.
        /// </summary>
        public static string CClockwise {
            get {
                return ResourceManager.GetString("CClockwise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chain.
        /// </summary>
        public static string Chain {
            get {
                return ResourceManager.GetString("Chain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Chart.
        /// </summary>
        public static string Chart {
            get {
                return ResourceManager.GetString("Chart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clockwise.
        /// </summary>
        public static string Clockwise {
            get {
                return ResourceManager.GetString("Clockwise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Note Settings.
        /// </summary>
        public static string CurrentNoteSettings {
            get {
                return ResourceManager.GetString("CurrentNoteSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Selection.
        /// </summary>
        public static string CurrentSelection {
            get {
                return ResourceManager.GetString("CurrentSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Mode.
        /// </summary>
        public static string DarkMode {
            get {
                return ResourceManager.GetString("DarkMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Gimmick.
        /// </summary>
        public static string DeleteGimmick {
            get {
                return ResourceManager.GetString("DeleteGimmick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Selected.
        /// </summary>
        public static string DeleteSelected {
            get {
                return ResourceManager.GetString("DeleteSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ↓ Snap.
        /// </summary>
        public static string DownArrowSnap {
            get {
                return ResourceManager.GetString("DownArrowSnap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Gimmick.
        /// </summary>
        public static string EditGimmick {
            get {
                return ResourceManager.GetString("EditGimmick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Selected.
        /// </summary>
        public static string EditSelected {
            get {
                return ResourceManager.GetString("EditSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Hold.
        /// </summary>
        public static string EndHold {
            get {
                return ResourceManager.GetString("EndHold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End of Chart.
        /// </summary>
        public static string EndOfChart {
            get {
                return ResourceManager.GetString("EndOfChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Exit.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _File.
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Center.
        /// </summary>
        public static string FromCenter {
            get {
                return ResourceManager.GetString("FromCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gimmick Types.
        /// </summary>
        public static string GimmickTypes {
            get {
                return ResourceManager.GetString("GimmickTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gimmick View.
        /// </summary>
        public static string GimmickView {
            get {
                return ResourceManager.GetString("GimmickView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlight Viewed Note.
        /// </summary>
        public static string HighlightViewedNote {
            get {
                return ResourceManager.GetString("HighlightViewedNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi-Speed:.
        /// </summary>
        public static string HiSpeed {
            get {
                return ResourceManager.GetString("HiSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hitsounds.
        /// </summary>
        public static string Hitsounds {
            get {
                return ResourceManager.GetString("Hitsounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hold.
        /// </summary>
        public static string Hold {
            get {
                return ResourceManager.GetString("Hold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial Chart Settings.
        /// </summary>
        public static string InitialChartSettings {
            get {
                return ResourceManager.GetString("InitialChartSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jump To Nearest Gimmick.
        /// </summary>
        public static string JumpToNearestGimmick {
            get {
                return ResourceManager.GetString("JumpToNearestGimmick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jump To Nearest Note.
        /// </summary>
        public static string JumpToNearestNote {
            get {
                return ResourceManager.GetString("JumpToNearestNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⤾ Slide.
        /// </summary>
        public static string LeftArrowSlide {
            get {
                return ResourceManager.GetString("LeftArrowSlide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mask.
        /// </summary>
        public static string Mask {
            get {
                return ResourceManager.GetString("Mask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mask Setting.
        /// </summary>
        public static string MaskSetting {
            get {
                return ResourceManager.GetString("MaskSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mask Value:.
        /// </summary>
        public static string MaskValue {
            get {
                return ResourceManager.GetString("MaskValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measure:.
        /// </summary>
        public static string Measure {
            get {
                return ResourceManager.GetString("Measure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N/A.
        /// </summary>
        public static string NA {
            get {
                return ResourceManager.GetString("NA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _New....
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Gimmick.
        /// </summary>
        public static string NextGimmick {
            get {
                return ResourceManager.GetString("NextGimmick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Note &gt;.
        /// </summary>
        public static string NextNote {
            get {
                return ResourceManager.GetString("NextNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Bonus.
        /// </summary>
        public static string NoBonus {
            get {
                return ResourceManager.GetString("NoBonus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        public static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes on Beat.
        /// </summary>
        public static string NotesOnBeat {
            get {
                return ResourceManager.GetString("NotesOnBeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note Types.
        /// </summary>
        public static string NoteTypes {
            get {
                return ResourceManager.GetString("NoteTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note View.
        /// </summary>
        public static string NoteView {
            get {
                return ResourceManager.GetString("NoteView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Open....
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place Note on Drag.
        /// </summary>
        public static string PlaceNoteOnDrag {
            get {
                return ResourceManager.GetString("PlaceNoteOnDrag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        public static string Play {
            get {
                return ResourceManager.GetString("Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playback.
        /// </summary>
        public static string Playback {
            get {
                return ResourceManager.GetString("Playback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position:.
        /// </summary>
        public static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Gimmick.
        /// </summary>
        public static string PreviousGimmick {
            get {
                return ResourceManager.GetString("PreviousGimmick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt; Previous Note.
        /// </summary>
        public static string PreviousNote {
            get {
                return ResourceManager.GetString("PreviousNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redo.
        /// </summary>
        public static string Redo {
            get {
                return ResourceManager.GetString("Redo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Mask.
        /// </summary>
        public static string RemoveMask {
            get {
                return ResourceManager.GetString("RemoveMask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reverse.
        /// </summary>
        public static string Reverse {
            get {
                return ResourceManager.GetString("Reverse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⤿ Slide.
        /// </summary>
        public static string RightArrowSlide {
            get {
                return ResourceManager.GetString("RightArrowSlide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R Note (Flair).
        /// </summary>
        public static string RNoteFlair {
            get {
                return ResourceManager.GetString("RNoteFlair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Save....
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Save As....
        /// </summary>
        public static string SaveAs {
            get {
                return ResourceManager.GetString("SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select File (*.ogg, *.wav, *.flac).
        /// </summary>
        public static string SelectFileOggWavFlac {
            get {
                return ResourceManager.GetString("SelectFileOggWavFlac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Last Inserted Note.
        /// </summary>
        public static string SelectLastInsertedNote {
            get {
                return ResourceManager.GetString("SelectLastInsertedNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Song.
        /// </summary>
        public static string SelectSong {
            get {
                return ResourceManager.GetString("SelectSong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Cursor.
        /// </summary>
        public static string ShowCursor {
            get {
                return ResourceManager.GetString("ShowCursor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Cursor During Playback.
        /// </summary>
        public static string ShowCursorDuringPlayback {
            get {
                return ResourceManager.GetString("ShowCursorDuringPlayback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Gimmicks During Playback.
        /// </summary>
        public static string ShowGimmicksDuringPlayback {
            get {
                return ResourceManager.GetString("ShowGimmicksDuringPlayback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Gimmicks In Circle View.
        /// </summary>
        public static string ShowGimmicksInCircleView {
            get {
                return ResourceManager.GetString("ShowGimmicksInCircleView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Measure Movement Buttons.
        /// </summary>
        public static string ShowMeasureMovementButtons {
            get {
                return ResourceManager.GetString("ShowMeasureMovementButtons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size:.
        /// </summary>
        public static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Song File:.
        /// </summary>
        public static string SongFile {
            get {
                return ResourceManager.GetString("SongFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed.
        /// </summary>
        public static string Speed {
            get {
                return ResourceManager.GetString("Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Signature.
        /// </summary>
        public static string TimeSignature {
            get {
                return ResourceManager.GetString("TimeSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Touch.
        /// </summary>
        public static string Touch {
            get {
                return ResourceManager.GetString("Touch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type:.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        public static string Undo {
            get {
                return ResourceManager.GetString("Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ↑ Snap.
        /// </summary>
        public static string UpArrowSnap {
            get {
                return ResourceManager.GetString("UpArrowSnap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value:.
        /// </summary>
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _View.
        /// </summary>
        public static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visual Settings.
        /// </summary>
        public static string VisualSettings {
            get {
                return ResourceManager.GetString("VisualSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume.
        /// </summary>
        public static string Volume {
            get {
                return ResourceManager.GetString("Volume", resourceCulture);
            }
        }
    }
}
